#include "indexedFddStorage.h"

extern template class indexedFddStorage<char, char>;
extern template class indexedFddStorage<char, int>;
extern template class indexedFddStorage<char, long int>;
extern template class indexedFddStorage<char, float>;
extern template class indexedFddStorage<char, double>;
extern template class indexedFddStorage<char, char *>;
extern template class indexedFddStorage<char, int *>;
extern template class indexedFddStorage<char, long int *>;
extern template class indexedFddStorage<char, float *>;
extern template class indexedFddStorage<char, double *>;
extern template class indexedFddStorage<char, std::string>;
extern template class indexedFddStorage<char, std::vector<char>>;
extern template class indexedFddStorage<char, std::vector<int>>;
extern template class indexedFddStorage<char, std::vector<long int>>;
extern template class indexedFddStorage<char, std::vector<float>>;
extern template class indexedFddStorage<char, std::vector<double>>;

extern template class indexedFddStorage<int, char>;
extern template class indexedFddStorage<int, int>;
extern template class indexedFddStorage<int, long int>;
extern template class indexedFddStorage<int, float>;
extern template class indexedFddStorage<int, double>;
extern template class indexedFddStorage<int, char *>;
extern template class indexedFddStorage<int, int *>;
extern template class indexedFddStorage<int, long int *>;
extern template class indexedFddStorage<int, float *>;
extern template class indexedFddStorage<int, double *>;
extern template class indexedFddStorage<int, std::string>;
extern template class indexedFddStorage<int, std::vector<char>>;
extern template class indexedFddStorage<int, std::vector<int>>;
extern template class indexedFddStorage<int, std::vector<long int>>;
extern template class indexedFddStorage<int, std::vector<float>>;
extern template class indexedFddStorage<int, std::vector<double>>;

extern template class indexedFddStorage<long int, char>;
extern template class indexedFddStorage<long int, int>;
extern template class indexedFddStorage<long int, long int>;
extern template class indexedFddStorage<long int, float>;
extern template class indexedFddStorage<long int, double>;
extern template class indexedFddStorage<long int, char *>;
extern template class indexedFddStorage<long int, int *>;
extern template class indexedFddStorage<long int, long int *>;
extern template class indexedFddStorage<long int, float *>;
extern template class indexedFddStorage<long int, double *>;
extern template class indexedFddStorage<long int, std::string>;
extern template class indexedFddStorage<long int, std::vector<char>>;
extern template class indexedFddStorage<long int, std::vector<int>>;
extern template class indexedFddStorage<long int, std::vector<long int>>;
extern template class indexedFddStorage<long int, std::vector<float>>;
extern template class indexedFddStorage<long int, std::vector<double>>;

extern template class indexedFddStorage<float, char>;
extern template class indexedFddStorage<float, int>;
extern template class indexedFddStorage<float, long int>;
extern template class indexedFddStorage<float, float>;
extern template class indexedFddStorage<float, double>;
extern template class indexedFddStorage<float, char *>;
extern template class indexedFddStorage<float, int *>;
extern template class indexedFddStorage<float, long int *>;
extern template class indexedFddStorage<float, float *>;
extern template class indexedFddStorage<float, double *>;
extern template class indexedFddStorage<float, std::string>;
extern template class indexedFddStorage<float, std::vector<char>>;
extern template class indexedFddStorage<float, std::vector<int>>;
extern template class indexedFddStorage<float, std::vector<long int>>;
extern template class indexedFddStorage<float, std::vector<float>>;
extern template class indexedFddStorage<float, std::vector<double>>;

extern template class indexedFddStorage<double, char>;
extern template class indexedFddStorage<double, int>;
extern template class indexedFddStorage<double, long int>;
extern template class indexedFddStorage<double, float>;
extern template class indexedFddStorage<double, double>;
extern template class indexedFddStorage<double, char *>;
extern template class indexedFddStorage<double, int *>;
extern template class indexedFddStorage<double, long int *>;
extern template class indexedFddStorage<double, float *>;
extern template class indexedFddStorage<double, double *>;
extern template class indexedFddStorage<double, std::string>;
extern template class indexedFddStorage<double, std::vector<char>>;
extern template class indexedFddStorage<double, std::vector<int>>;
extern template class indexedFddStorage<double, std::vector<long int>>;
extern template class indexedFddStorage<double, std::vector<float>>;
extern template class indexedFddStorage<double, std::vector<double>>;

extern template class indexedFddStorage<std::string, char>;
extern template class indexedFddStorage<std::string, int>;
extern template class indexedFddStorage<std::string, long int>;
extern template class indexedFddStorage<std::string, float>;
extern template class indexedFddStorage<std::string, double>;
extern template class indexedFddStorage<std::string, char *>;
extern template class indexedFddStorage<std::string, int *>;
extern template class indexedFddStorage<std::string, long int *>;
extern template class indexedFddStorage<std::string, float *>;
extern template class indexedFddStorage<std::string, double *>;
extern template class indexedFddStorage<std::string, std::string>;
extern template class indexedFddStorage<std::string, std::vector<char>>;
extern template class indexedFddStorage<std::string, std::vector<int>>;
extern template class indexedFddStorage<std::string, std::vector<long int>>;
extern template class indexedFddStorage<std::string, std::vector<float>>;
extern template class indexedFddStorage<std::string, std::vector<double>>;

