#include "workerIFdd.h"

extern template class workerIFdd<char, char>;
extern template class workerIFdd<char, int>;
extern template class workerIFdd<char, long int>;
extern template class workerIFdd<char, float>;
extern template class workerIFdd<char, double>;
extern template class workerIFdd<char, char*>;
extern template class workerIFdd<char, int*>;
extern template class workerIFdd<char, long int*>;
extern template class workerIFdd<char, float*>;
extern template class workerIFdd<char, double*>;
extern template class workerIFdd<char, std::string>;
extern template class workerIFdd<char, std::vector<char>>;
extern template class workerIFdd<char, std::vector<int>>;
extern template class workerIFdd<char, std::vector<long int>>;
extern template class workerIFdd<char, std::vector<float>>;
extern template class workerIFdd<char, std::vector<double>>;
 
extern template class workerIFdd<int, char>;
extern template class workerIFdd<int, int>;
extern template class workerIFdd<int, long int>;
extern template class workerIFdd<int, float>;
extern template class workerIFdd<int, double>;
extern template class workerIFdd<int, char*>;
extern template class workerIFdd<int, int*>;
extern template class workerIFdd<int, long int*>;
extern template class workerIFdd<int, float*>;
extern template class workerIFdd<int, double*>;
extern template class workerIFdd<int, std::string>;
extern template class workerIFdd<int, std::vector<char>>;
extern template class workerIFdd<int, std::vector<int>>;
extern template class workerIFdd<int, std::vector<long int>>;
extern template class workerIFdd<int, std::vector<float>>;
extern template class workerIFdd<int, std::vector<double>>;
 
extern template class workerIFdd<long int, char>;
extern template class workerIFdd<long int, int>;
extern template class workerIFdd<long int, long int>;
extern template class workerIFdd<long int, float>;
extern template class workerIFdd<long int, double>;
extern template class workerIFdd<long int, char*>;
extern template class workerIFdd<long int, int*>;
extern template class workerIFdd<long int, long int*>;
extern template class workerIFdd<long int, float*>;
extern template class workerIFdd<long int, double*>;
extern template class workerIFdd<long int, std::string>;
extern template class workerIFdd<long, std::vector<char>>;
extern template class workerIFdd<long, std::vector<int>>;
extern template class workerIFdd<long, std::vector<long int>>;
extern template class workerIFdd<long, std::vector<float>>;
extern template class workerIFdd<long, std::vector<double>>;
 
extern template class workerIFdd<float, char>;
extern template class workerIFdd<float, int>;
extern template class workerIFdd<float, long int>;
extern template class workerIFdd<float, float>;
extern template class workerIFdd<float, double>;
extern template class workerIFdd<float, char*>;
extern template class workerIFdd<float, int*>;
extern template class workerIFdd<float, long int*>;
extern template class workerIFdd<float, float*>;
extern template class workerIFdd<float, double*>;
extern template class workerIFdd<float, std::string>;
extern template class workerIFdd<float, std::vector<char>>;
extern template class workerIFdd<float, std::vector<int>>;
extern template class workerIFdd<float, std::vector<long int>>;
extern template class workerIFdd<float, std::vector<float>>;
extern template class workerIFdd<float, std::vector<double>>;
 
extern template class workerIFdd<double, char>;
extern template class workerIFdd<double, int>;
extern template class workerIFdd<double, long int>;
extern template class workerIFdd<double, float>;
extern template class workerIFdd<double, double>;
extern template class workerIFdd<double, char*>;
extern template class workerIFdd<double, int*>;
extern template class workerIFdd<double, long int*>;
extern template class workerIFdd<double, float*>;
extern template class workerIFdd<double, double*>;
extern template class workerIFdd<double, std::string>;
extern template class workerIFdd<double, std::vector<char>>;
extern template class workerIFdd<double, std::vector<int>>;
extern template class workerIFdd<double, std::vector<long int>>;
extern template class workerIFdd<double, std::vector<float>>;
extern template class workerIFdd<double, std::vector<double>>;
 
extern template class workerIFdd<std::string, char>;
extern template class workerIFdd<std::string, int>;
extern template class workerIFdd<std::string, long int>;
extern template class workerIFdd<std::string, float>;
extern template class workerIFdd<std::string, double>;
extern template class workerIFdd<std::string, char*>;
extern template class workerIFdd<std::string, int*>;
extern template class workerIFdd<std::string, long int*>;
extern template class workerIFdd<std::string, float*>;
extern template class workerIFdd<std::string, double*>;
extern template class workerIFdd<std::string, std::string>;
extern template class workerIFdd<std::string, std::vector<char>>;
extern template class workerIFdd<std::string, std::vector<int>>;
extern template class workerIFdd<std::string, std::vector<long int>>;
extern template class workerIFdd<std::string, std::vector<float>>;
extern template class workerIFdd<std::string, std::vector<double>>;

